cmake: Check for C++-17 and conditionally enable it
KhronosGroup/OpenXR-SDK-Source pull request #188
Opened 2020-05-06 09:24 UTC by philn

In GCC __cplusplus will be 201703 only if the -std=c++17 option is passed to the
compiler. Without this option the filesystem_utils.cpp won't compile under GCC
9.3.0, giving the following error:

src/common/filesystem_utils.cpp:74:10: fatal error: experimental/filesystem: No
such file or directory

2020-05-06 09:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenXR-SDK-Source?pullRequest=188) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenXR-SDK-Source?pullRequest=188) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenXR-SDK-Source?pullRequest=188) it.</sub>

2020-05-07 15:17 UTC, rpavlik commented
Ah, so they have removed the experimental headers in 9.3.0? In the older versions of GCC (and libstdc++) I've used, the C++14 setting that's on now is enough to get the experimental filesystem support. I'll look closer at this soon.

2020-05-07 18:39 UTC, philn commented
From what I can see here, the `filesystem` header is indeed no longer in `experimental/`.

2020-05-13 21:09 UTC, rpavlik commented
Thanks for doing this! Can you test and see if the branch in #192 works for you? I ended up making a fairly dramatic change, and actually checking to see if we could build using experimental/filesystem and filesystem (and filesystem with c++17 enabled), as well as then checking if we needed stdc++fs (since I can build c++17 mode here on Debian Buster with 8.3, but still need stdc++fs) to make it compile.

2020-05-13 21:21 UTC, rpavlik requested changes

2020-05-13 21:21 UTC, rpavlik commented on src/CMakeLists.txt
> +    check_cxx_compiler_flag(-std=c++17 HAVE_FLAG_STD_CXX17)
I think the best way to do this that I've found is to search `CMAKE_CXX_COMPILE_FEATURES` for `cxx_std_17`:

```
list(FIND CMAKE_CXX_COMPILE_FEATURES cxx_std_17 cxx17_index)
if(NOT ${cxx17_index} EQUAL -1)
    set(CMAKE_CXX_STANDARD 17)
endif()
```

This currently will not behave as desired on MSVC.

This change could be rebased on top of #192 - it's no longer needed to make it build on gcc 9.3.0 (I hope!) but it would still be worth considering an "opportunistic" upgrade to C++17.

2020-05-13 21:21 UTC, rpavlik commented on src/loader/CMakeLists.txt
> +            openxr_loader
So this could be split into two `target_link_libraries` calls - one with just m, and one with stdc++fs. However, m isn't apparently actually needed, and at least on my gcc 8.3.0, I need stdc++fs even though I have c++17 support. I'd suggest just dropping this part of the patch when rebasing on #192 since that handles it in a more complete way.

2020-05-28 22:32 UTC, rpavlik commented
Closing because #192 was merged and was reported to fix the issue.

2020-05-28 22:32 UTC, closed without merging