Work around std::filesystem::canonical bug on UWP
KhronosGroup/OpenXR-SDK-Source pull request #198
Opened 2020-08-02 22:04 UTC by brycehutchings

We found a change in the 1.0.10 loader to use std::filesystem::canonical broke UWP apps on Windows (used mostly for HoloLens 2). Based on my investigation this STL function is broken on the UWP platform and always fails with an access denied error code. I will be opening a bug on the Microsoft STL about this. The use of canonical was introduced for Linux so that a relative path in a JSON manifest would be relative to the real manifest file and not the symbol link path. This functionality is not important on Windows because the registry is used for redirection instead, and so symbol links are not needed and their use is also uncommon on Windows. For this reason PathCchCanonicalize is used instead of std::filesystem::canonical on Windows. This also fixes #197 by replacing use of PathCanonicalize with PathCchCanonicalize which is documented as the recommended API.

2020-08-03 15:32 UTC, rpavlik requested changes
Ah, good catch. I know the canonical check was tested on Windows with/without std::filesystem but I imagine the contributor didn't try building for HoloLens. Just add the changelog fragment and it'll be good to go!

2020-08-03 23:50 UTC, brycehutchings commented
Sorry I appear to be incapable of remembering to include the changelog fragment!

2020-08-04 20:17 UTC, yl-msft approved these changes

2020-08-04 20:17 UTC, yl-msft commented on src/common/filesystem_utils.cpp
> +    if (FAILED(PathCchCanonicalize(canonical_wide_path, MAX_PATH, utf8_to_wide(path).c_str()))) {
don't we add "W" at these functions to force them wchar version?

2020-08-04 20:37 UTC, brycehutchings commented on src/common/filesystem_utils.cpp
> +    if (FAILED(PathCchCanonicalize(canonical_wide_path, MAX_PATH, utf8_to_wide(path).c_str()))) {
yeah seems like a good idea!

2020-08-04 20:38 UTC, brycehutchings commented on src/common/filesystem_utils.cpp
> +    if (FAILED(PathCchCanonicalize(canonical_wide_path, MAX_PATH, utf8_to_wide(path).c_str()))) {
Actually PathCchCanonicalize is wide only

2020-08-05 20:43 UTC, merged

2020-08-06 15:02 UTC, rpavlik commented on src/common/filesystem_utils.cpp
> +    if (FAILED(PathCchCanonicalize(canonical_wide_path, MAX_PATH, utf8_to_wide(path).c_str()))) {
isn't max_path an artificial limitation when using wide apis now?

2020-08-06 16:12 UTC, brycehutchings commented on src/common/filesystem_utils.cpp
> +    if (FAILED(PathCchCanonicalize(canonical_wide_path, MAX_PATH, utf8_to_wide(path).c_str()))) {
It's not related to wide characters per-se. We can use a bigger number, but many parts of windows use MAX_PATH so it is a bit of an unfortunate de-facto limit in Windows. Another option is to use PathCchCanonicalizeEx and dynamically allocate the buffer to the length needed. What I did was a bit of a lazy but common pattern in Windows programming.

2020-08-06 16:25 UTC, rpavlik commented on src/common/filesystem_utils.cpp
> +    if (FAILED(PathCchCanonicalize(canonical_wide_path, MAX_PATH, utf8_to_wide(path).c_str()))) {
ah, ok. That will work until it doesn't. :)

2020-08-06 16:26 UTC, rpavlik commented on src/common/filesystem_utils.cpp
> +    if (FAILED(PathCchCanonicalize(canonical_wide_path, MAX_PATH, utf8_to_wide(path).c_str()))) {
there, filed an issue on it so we don't forget :)

2020-08-07 22:11 UTC, chrisfromwork commented
@rpavlik  do you know when this change will make it into the OpenXR-SDK repo?

2020-08-08 02:48 UTC, rpavlik commented
Next patch release at the latest. Should be very soon.