Add file formatting checks to CI
KhronosGroup/OpenXR-SDK-Source pull request #209
Opened 2020-09-19 08:04 UTC by aaronfranke

Follow-up to #208. Fingers crossed that the CI checks will work, in previous implementations I had this script set up through GitHub Actions, but since this repo uses Azure Pipelines I used that instead.

2020-11-24 15:57 UTC, rpavlik requested changes
Thanks for this! I have a few comments, but I do like the general idea and I have used it before the upcoming release despite not merging it yet.

2020-11-24 15:57 UTC, rpavlik commented on file_format.sh
> +#!/usr/bin/env bash
Need copyright and license statement. If in doubt, use this one:

```
# Copyright (c) 2020 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0
```

2020-11-24 15:57 UTC, rpavlik commented on .azure-pipelines/check_file_format.yml
> +
Needs copyright/license: see other comment for sample.

2020-11-24 15:57 UTC, rpavlik commented on file_format.sh
> +    perl -i -pe 's/\x20== true//g' "$f"
This seems not necessary.

2020-11-24 15:57 UTC, rpavlik commented on file_format.sh
> +git grep -zIl '' |
is this basically supposed to do the same thing as `git ls-files`? Somehow it manages to break running from WSL - it's trying to access stuff using the Windows file path instead of the corresponding Linux one. Unfortunately it still gives the same error with git ls-files thru wsl.

```
ryanp@RYZENSHINE-WIN  E:\src-ssd\OpenXR-SDK-Source   format-ci ≢ +3 ~1 -0 !                                [09:56]
❯ wsl ./file_format.sh
fatal: cannot chdir to 'E:/src-ssd/OpenXR-SDK-Source': No such file or directory
fatal: cannot chdir to 'E:/src-ssd/OpenXR-SDK-Source': No such file or directory
Files in this commit comply with the formatting rules.
```

2020-11-24 15:57 UTC, rpavlik commented on file_format.sh
> +    printf "Install 'dos2unix' and 'recode' to use this script.\n"
why printf? and should we `exit 1` here? or just `exit 0` to avoid failing CI if I am missing the right stuff in the docker image?

2020-11-24 15:57 UTC, rpavlik commented on changes/sdk/pr.206.gh.OpenXR-SDK-Source.md
> +cmake: fix openxr_loader target export when installing both Release and Debug config on Windows.
please drop this change (when rebasing) to solve the conflict

2020-11-24 15:57 UTC, rpavlik commented on file_format.sh
> +set -uo pipefail
probably `set -e` in here too, since I'm getting:

```
ryan@RyZenShine-Win:/mnt/e/src-ssd/OpenXR-SDK-Source$ ./file_format.sh
fatal: cannot chdir to 'E:/src-ssd/OpenXR-SDK-Source': No such file or directory
fatal: cannot chdir to 'E:/src-ssd/OpenXR-SDK-Source': No such file or directory
Files in this commit comply with the formatting rules.
```

2020-11-24 15:57 UTC, rpavlik commented on file_format.sh
> +git diff > patch.patch
I think `git diff --exit-code` can be your friend here - it's what we use in gitlab ci.

2020-11-24 15:57 UTC, rpavlik commented on file_format.sh
> +rm -f patch.patch
I think ideally we should archive the patch as an artifact, instead of deleting it, so it's easy to fix.

2020-11-24 21:34 UTC, aaronfranke commented on file_format.sh
> +git grep -zIl '' |
The difference between this code and `git ls-files` is that `git ls-files` includes binary files but the above code excludes them. We don't want to try converting a PNG file to UTF-8 for example.

I'm not sure what to do to make this work for WSL. The `git grep -zIl '' |` line works on Linux as-is, and `IFS=$'\n\t'` was added for compatibility with Mac and BSDs.

2020-11-24 21:36 UTC, aaronfranke commented on file_format.sh
> +rm -f patch.patch
When modifying files locally, the easiest solution I could think of was to just have it delete the patch. If you want to archive this somewhere instead, that's a decent idea, but note that it's already printed to the terminal with `cat patch.patch`, so if you have access to the CI's terminal output then you're all set.

2020-11-24 21:43 UTC, aaronfranke commented on file_format.sh
> +    printf "Install 'dos2unix' and 'recode' to use this script.\n"
I don't remember why `printf` was used, it might be another case of BSD compatibility.

`exit 1` or `exit 0` are up to you. Without them, the script will warn you when these tools are missing but still run what it can. If there is an exit here, I think `exit 1` makes more sense.

2020-11-24 21:48 UTC, aaronfranke commented on file_format.sh
> +git diff > patch.patch
Sure. `if git diff --exit-code > patch.patch; then` works fine.

2020-11-24 21:54 UTC, rpavlik commented on file_format.sh
> +rm -f patch.patch
true, though I will confess it's probably challenging to copy and paste a mostly-whitespace or BOM patch from a terminal output log on a web page ;)

2020-12-17 04:33 UTC, aaronfranke commented
@rpavlik Requesting review and merge. I'm not sure what else I can do with this PR, I've responded to your feedback as well as I can. I think the best course of action is to merge it, and then you can make any further changes as needed.

2020-12-17 18:18 UTC, rpavlik commented
sorry for not merging this sooner - it looks good, I was just having some trouble getting it to run on our CI. I did run it before the last release, I think, despite not being able to merge. This one is on me now.

2020-12-17 18:19 UTC, rpavlik approved these changes

2021-04-02 16:37 UTC, rpavlik commented on file_format.sh
> +git grep -zIl '' |
ah, it was a git worktree config thing.

2021-04-02 16:38 UTC, rpavlik approved these changes

2021-04-02 16:38 UTC, merged

2021-04-02 16:40 UTC, rpavlik commented
Thanks - figured out my wsl problem and got it merged!