Using d suffix for debug library in Windows
KhronosGroup/OpenXR-SDK-Source pull request #229
Opened 2020-11-23 06:29 UTC by matthieucoquet

Before this change, openxr-loader debug library was put in a `Debug` directory during install.
Now, the library would have a suffix and be in the same directory as the release library. 

The suffix is `d` by default on Windows and is empty on Linux. It can be changed or removed using the `OPENXR_DEBUG_POSTFIX` variable:
```
cmake -dOPENXR_DEBUG_POSTFIX=my_suffix path_to_repo
```

In addition, I did a small clean for the `headers` target. Instead of manually define it in `OpenXRConfig.cmake.in`. I define it and export it in the `CMakeLists.txt`

I tested on Windows for static and dynamic lib and also on Linux.

2020-11-23 19:16 UTC, rpavlik requested changes

2020-11-23 19:16 UTC, rpavlik commented on src/loader/CMakeLists.txt
> +set(OPENXR_DEBUG_POSTFIX d CACHE STRING "OpenXR loader debug postfix.")
Will this override any user-supplied values?

2020-11-23 19:16 UTC, rpavlik commented on src/loader/OpenXRConfig.cmake.in
> -add_library(OpenXR::headers INTERFACE IMPORTED)
so does this then remove the "headers" imported target?

2020-11-24 04:58 UTC, matthieucoquet commented on src/loader/OpenXRConfig.cmake.in
> -add_library(OpenXR::headers INTERFACE IMPORTED)
The `headers` target is now defined in `src/loader/CMakeLists.txt` at line 249 and exported at line 253. I think it's cleaner to define it this way.

2020-11-24 05:07 UTC, matthieucoquet commented on src/loader/CMakeLists.txt
> +set(OPENXR_DEBUG_POSTFIX d CACHE STRING "OpenXR loader debug postfix.")
I think this override the global `CMAKE_DEBUG_POSTFIX` if it's set. I didn't want to use `CMAKE_DEBUG_POSTFIX` directly because it applies the suffix to all targets. I think it's better to have per target settings, that's why I created a new `OPENXR_DEBUG_POSTFIX` variable.

2020-11-24 15:34 UTC, rpavlik commented on src/loader/CMakeLists.txt
> +set(OPENXR_DEBUG_POSTFIX d CACHE STRING "OpenXR loader debug postfix.")
I mean if the user sets OPENXR_DEBUG_POSTFIX themselves on the command line?

I suspect we want to wrap that all in `if(NOT DEFINED OPENXR_DEBUG_POSTFIX)`

2020-11-24 15:34 UTC, rpavlik commented on src/loader/OpenXRConfig.cmake.in
> -add_library(OpenXR::headers INTERFACE IMPORTED)
Ah, OK, I had missed that in the diff review

2020-11-25 04:31 UTC, matthieucoquet commented on src/loader/CMakeLists.txt
> +set(OPENXR_DEBUG_POSTFIX d CACHE STRING "OpenXR loader debug postfix.")
This line doesn't override OPENXR_DEBUG_POSTFIX is it's set on the command line. I checked it on my side to make sure the user can choose the postfix.

The [documentation](https://cmake.org/cmake/help/v3.19/command/set.html) states that:
> It is possible for the cache entry to exist prior to the call but have no type set if it was created on the cmake(1) command line by a user through the `-D<var>=<value>` option without specifying a type. In this case the set command will add the type. 

So there is no need for additional if statement.

2020-11-25 17:43 UTC, rpavlik commented on src/loader/CMakeLists.txt
> +set(OPENXR_DEBUG_POSTFIX d CACHE STRING "OpenXR loader debug postfix.")
oh interesting... and I suppose if it's set by a "super-project" it also won't overwrite the value since there's no `FORCE` in the command.  I had no idea, my cmake scripts are probably more complicated than required as a result...

2020-11-26 13:18 UTC, matthieucoquet commented on src/loader/CMakeLists.txt
> +set(OPENXR_DEBUG_POSTFIX d CACHE STRING "OpenXR loader debug postfix.")
Yes, if the super-project declares a cached variable first, it won't be overwritten.

2021-01-26 17:07 UTC, rpavlik approved these changes
I've rebased this, made a few minor tweaks, and merged it. Thanks!

2021-01-26 17:08 UTC, closed without merging