Remove canonicalization in Windows loader
KhronosGroup/OpenXR-SDK-Source pull request #239
Opened 2021-02-01 18:37 UTC by brycehutchings

To fix the OpenXR loader on Windows 7, I am making the filesystem canonicalization function a no-op. Canonicalization was added for Linux support to follow a symlink, but symlinks are not used on Windows and there is no canonicalization function that can be used everywhere.

2021-02-01 19:32 UTC, JoeLudwig approved these changes

2021-02-11 17:36 UTC, rpavlik requested changes
I think you added a submodule "DiligentEngine" by accident here. Also, good to mention the various issues in the front-matter of the changelog fragment.

2021-02-11 17:38 UTC, brycehutchings commented
> I think you added a submodule "DiligentEngine" by accident here. Also, good to mention the various issues in the front-matter of the changelog fragment.

Crap, my hobby project leaked in... good catch.

2021-02-11 18:29 UTC, rpavlik approved these changes

2021-02-11 18:29 UTC, merged