Fix not finding 'wayland-client.h' in submodule build
KhronosGroup/OpenXR-SDK-Source pull request #346
Opened 2022-11-16 11:41 UTC by rhabacker

Building openxr when included as a submodule in another project fails because the mentioned header file was not found.

2022-11-16 23:10 UTC, rpavlik requested changes
I think this won't work when not using Wayland (and in fact the OpenGL wayland bindings in OpenXR are flawed and mostly unusable, apparently), please revise as noted. Also, please add a changelog fragment to changes/sdk named `pr.246.gh.OpenXR-SDK-Source.md` describing your change in about a sentence.

2022-11-16 23:10 UTC, rpavlik commented on src/loader/CMakeLists.txt
> +            ${WAYLAND_CLIENT_INCLUDE_DIRS}
Hmm, the loader shouldn't need to include wayland, what is the error you get? In any case, it should only have that include if the wayland build is actually chosen, I believe, rather than unconditionally.

2022-11-17 07:46 UTC, rhabacker commented on src/loader/CMakeLists.txt
> +            ${WAYLAND_CLIENT_INCLUDE_DIRS}
Compiling the loader (and targets in the api_layers subdirectory) depends on that file.
```
Consolidate compiler generated dependencies of target openxr_loader
[ 31%] Building CXX object src/loader/CMakeFiles/openxr_loader.dir/loader_instance.cpp.o
[ 31%] Building CXX object src/loader/CMakeFiles/openxr_loader.dir/android_utilities.cpp.o
[ 34%] Building CXX object src/loader/CMakeFiles/openxr_loader.dir/manifest_file.cpp.o
[ 34%] Building CXX object src/loader/CMakeFiles/openxr_loader.dir/loader_logger_recorders.cpp.o
[ 36%] Building CXX object src/loader/CMakeFiles/openxr_loader.dir/loader_core.cpp.o
[ 37%] Building CXX object src/loader/CMakeFiles/openxr_loader.dir/api_layer_interface.cpp.o
[ 38%] Building CXX object src/loader/CMakeFiles/openxr_loader.dir/loader_logger.cpp.o
[ 40%] Building CXX object src/loader/CMakeFiles/openxr_loader.dir/runtime_interface.cpp.o
[ 41%] Building C object src/loader/CMakeFiles/openxr_loader.dir/__/xr_generated_dispatch_table.c.o
In file included from /home/xxx/src/vsgvr/deps/openxr/src/loader/loader_platform.hpp:16:0,
                 from /home/xxx/src/vsgvr/deps/openxr/src/loader/api_layer_interface.hpp:18,
                 from /home/xxx/src/vsgvr/deps/openxr/src/loader/loader_core.cpp:14:
/home/xxx/src/vsgvr/deps/openxr/src/common/xr_dependencies.h:88:10: fatal error: wayland-client.h: Datei oder Verzeichnis nicht gefunden
 #include "wayland-client.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/loader/CMakeFiles/openxr_loader.dir/build.make:120: src/loader/CMakeFiles/openxr_loader.dir/loader_core.cpp.o] Fehler 1
```

2022-11-17 07:50 UTC, rhabacker commented
> named pr.246.gh.OpenXR-SDK-Source.md describing your change in about a sentence.

Really ? Not pr.346.gh.OpenXR-SDK-Source.md

2022-11-17 08:10 UTC, rhabacker commented
It looks that the required CI job `KhronosGroup.OpenXR-SDK-Source` blocks this pr with an error not related to this pr:

> The nuget command failed with exit code(1) and error(System.InvalidOperationException: The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has invalid child element

2022-11-17 14:57 UTC, rpavlik commented
> > named pr.246.gh.OpenXR-SDK-Source.md describing your change in about a sentence.
> 
> Really ? Not pr.346.gh.OpenXR-SDK-Source.md

you're right, that was a typo.

Yeah, I have to figure out what's going on with those two CI jobs, don't mind them.

2023-01-20 20:25 UTC, rpavlik approved these changes

2023-01-20 20:26 UTC, merged

2023-01-20 20:26 UTC, rpavlik commented
Thanks for this, it will be in the next release!