Add 'unknown' strings to loader's *ToString fallback functions
KhronosGroup/OpenXR-SDK-Source pull request #35
Opened 2019-04-18 17:52 UTC by daveh-lunarg

The loader's fallback implementation of ResultToString and StructureToString did not correctly fill the string buffer when an unrecognized result or structure was provided.

Fixes #33

2019-04-18 21:41 UTC, brycehutchings requested changes

2019-04-18 21:41 UTC, brycehutchings commented on src/scripts/utility_source_generator.py
> +        result_to_str += 'snprintf(buffer, XR_MAX_RESULT_STRING_SIZE, "XR_UNKNOWN_SUCCESS_%1u", (uint32_t)result);\n'
'result' doesn't need to be casted AFAIK (or it could be casted as int32_t like the failure case). It will still be positive as the spec requires because it is in the XR_SUCCEEDED code path.

2019-04-18 21:41 UTC, brycehutchings commented on src/scripts/utility_source_generator.py
> +        result_to_str += 'snprintf(buffer, XR_MAX_RESULT_STRING_SIZE, "XR_UNKNOWN_SUCCESS_%1u", (uint32_t)result);\n'
Also the 1 in "%1d" will cause it have a minimum field width of "1" (aligned to the right). Was this the intent? It doesn't seem necessary.

2019-04-18 21:41 UTC, brycehutchings commented on src/scripts/utility_source_generator.py
> +        result_to_str += 'snprintf(buffer, XR_MAX_RESULT_STRING_SIZE, "XR_UNKNOWN_SUCCESS_%1u", (uint32_t)result);\n'
I would recommend no casting for any of these three enums being passed into snprintf.

2019-04-19 18:01 UTC, daveh-lunarg commented on src/scripts/utility_source_generator.py
> +        result_to_str += 'snprintf(buffer, XR_MAX_RESULT_STRING_SIZE, "XR_UNKNOWN_SUCCESS_%1u", (uint32_t)result);\n'
Old habits. Agreed that the casts and size 1 field width are no-ops.  (I'm sure each of them represent something that bit me somehow, some time in the last several decades, but I can't dredge up an example :)

2019-04-19 18:15 UTC, daveh-lunarg commented
I want to push this PR for correctness and to close the issue. But, in the end I'm becoming more convinced that the loader shouldn't provide these API entry points at all. (See discussion of https://gitlab.khronos.org/openxr/openxr/issues/980)

Assuming that view prevails, these util functions will eventually be removed.

2019-04-19 20:14 UTC, brycehutchings approved these changes

2019-04-24 20:15 UTC, merged

2019-04-24 20:51 UTC, rpavlik commented
you beat me to the review :) looks good, thanks.