OpenXR loader: partial fix for XRLOADER_DISABLE_EXCEPTION_HANDLING
KhronosGroup/OpenXR-SDK-Source pull request #405
Opened 2023-05-10 21:20 UTC by bialpio

Work left: adjust JNIPP to support no-exceptions mode.

Tested by building the following two configurations (based on the parameters that maintainer-scripts/build-aar.sh script is passing to cmake):
`cmake -S . -B out/exceptions -G Ninja -DCMAKE_TOOLCHAIN_FILE=/usr/local/google/code/clankium/src/third_party/android_ndk/build/cmake/android.toolchain.cmake -DCMAKE_ANDROID_NDK=/usr/local/google/code/clankium/src/third_party/android_ndk/ -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=24 -DANDROID_STL=c++_static -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -DBUILD_CONFORMANCE_TESTS=OFF -DBUILD_LOADER=ON -DBUILD_API_LAYERS=OFF`

`cmake -S . -B out/no-exceptions -G Ninja -DCMAKE_TOOLCHAIN_FILE=/usr/local/google/code/clankium/src/third_party/android_ndk/build/cmake/android.toolchain.cmake -DCMAKE_ANDROID_NDK=/usr/local/google/code/clankium/src/third_party/android_ndk/ -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=24 -DANDROID_STL=c++_static -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -DBUILD_CONFORMANCE_TESTS=OFF -DBUILD_LOADER=ON -DBUILD_API_LAYERS=OFF -DBUILD_LOADER_WITH_EXCEPTION_HANDLING=OFF`

2023-05-10 21:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenXR-SDK-Source?pullRequest=405) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenXR-SDK-Source?pullRequest=405) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenXR-SDK-Source?pullRequest=405) it.</sub>

2023-06-07 20:46 UTC, rpavlik requested changes
Looks reasonable to me. Does it make sense to merge this without the rest of the changes?

Can you add a changelog fragment in `changes/sdk/pr.405.gh.OpenXR-SDK-Source.md` per the readme in that directory?

2023-06-08 18:21 UTC, bialpio commented
> Looks reasonable to me. Does it make sense to merge this without the rest of the changes?

IMO yes - depending on how downstream consumers compile the loader, it'd allow them to immediately start compiling itw/o exceptions, but still compile the JNIPP with exceptions.

> Can you add a changelog fragment in `changes/sdk/pr.405.gh.OpenXR-SDK-Source.md` per the readme in that directory?

Done, please take a look.

2023-06-20 18:06 UTC, bialpio commented
Gentle ping - @rpavlik, can you take a look?

2023-11-29 22:07 UTC, rpavlik commented
Updated version of this patch merged in internal tree, released with 1.0.32

2023-11-29 22:07 UTC, closed without merging