Add support for loongarch64
KhronosGroup/OpenXR-SDK-Source pull request #479
Opened 2024-06-04 03:33 UTC by qiangxuhui

Fix build on linux/loongarch64.

2024-06-04 03:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenXR-SDK-Source?pullRequest=479) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenXR-SDK-Source?pullRequest=479) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenXR-SDK-Source?pullRequest=479) it.</sub>

2024-06-04 18:08 UTC, rpavlik commented
We will need you to sign the CLA. In addition, this should be added to the table in the loader design doc alongside the rest of the platforms.

Also, we tend to follow Debian, who uses loong64 as the architecture name: https://wiki.debian.org/Ports/loong64

2024-06-04 20:27 UTC, Perksey commented
I don't think Loongson can sign a Khronos Group agreement due to U.S. sanctions.

2024-06-05 03:16 UTC, qiangxuhui commented
@rpavlik PTAL.

2024-06-05 05:16 UTC, utzcoz commented
@qiangxuhui I think you need a separate commit for change fragment. You can check other merged PRs on GitHub to see what it means.

2024-06-06 09:06 UTC, qiangxuhui commented
@utzcoz Done.

2024-09-23 15:44 UTC, rpavlik commented on specification/loader/runtime.adoc
> +  | 64-bit LoongArch architecture, little endian
Can we assume LP64D ABI here? (including the double-precision hard float)  If so, probably worth mentioning that ABI name, similar to e.g. armv7a-vfp

2024-09-23 15:46 UTC, rpavlik requested changes
Name looks good, matches Debian. Just one question about the specific ABI, and then I'll request working group approval to merge.

2024-09-27 18:15 UTC, rpavlik commented on specification/loader/runtime.adoc
> +  | 64-bit LoongArch architecture, little endian
Once this is resolved, I have approval to merge this, the WG has approved it.

2024-10-21 06:56 UTC, qiangxuhui commented
@rpavlik Done.

2024-10-21 16:14 UTC, rpavlik approved these changes
Thanks for updating this!

2024-10-21 16:28 UTC, merged