ci: Add GitHub Action for macOS building
KhronosGroup/OpenXR-SDK-Source pull request #501
Opened 2024-09-15 08:57 UTC by utzcoz

1. macos-14 for arm64 macOS.

Looks like humbletim/setup-vulkan-sdk's cache mechanism doesn't work for multiple jobs with the same OS but different architectures, like macOS 13 is x86_64 and macOS 14 is arm64. So this CL only adds macos-14 as runner OS and we can enable the macos-13 when we fixed the upstream cache supporting.

2024-09-16 21:27 UTC, rpavlik requested changes
OK, this is awesome, thank you! I just have one little issue where I think it's not actually building, but otherwise this is great.

2024-09-16 21:27 UTC, rpavlik commented on .github/workflows/macOS.yml
> +          cmake -G "Xcode" ../..
looks like this maybe only generates, and doesn't build?

Also I typically use the `-S` and `-B` args to cmake these days to specify source and build dir. Avoids having to make directories, change directory, etc.

2024-09-17 08:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/KhronosGroup/OpenXR-SDK-Source?pullRequest=501) <br/>All committers have signed the CLA.

2024-09-17 09:38 UTC, utzcoz commented on .github/workflows/macOS.yml
> +          cmake -G "Xcode" ../..
Thanks. I updated the command to build on macOS with xcodebuild.

2024-09-21 07:19 UTC, utzcoz commented
@rpavlik PTAL.

2024-09-23 15:21 UTC, rpavlik approved these changes
Looks good, thanks! I made a few minor tweaks.

2024-09-23 15:47 UTC, merged