Fix build error with shlwapi function
KhronosGroup/OpenXR-SDK-Source pull request #60
Opened 2019-06-17 18:18 UTC by zheqiMicrosoft

Really sorry for making this mistake. (I forgot to explicitly disable std::filesystem when trying to build) I just realized that there are several other places I have to use the A version explicitly.

2019-06-17 21:30 UTC, rpavlik commented
Can't rebase this automatically on master - can you do that (or just cherry-pick the one commit on top of master), or would you prefer that I do?

2019-06-17 21:31 UTC, zheqiMicrosoft commented
I will do that. Thanks.

Best,
Kevin

________________________________
发件人: Ryan A. Pavlik <notifications@github.com>
发送时间: Monday, June 17, 2019 2:30:06 PM
收件人: KhronosGroup/OpenXR-SDK
抄送: Kevin Qin; Author
主题: Re: [KhronosGroup/OpenXR-SDK] Fix build error with shlwapi function (#60)


Can't rebase this automatically on master - can you do that (or just cherry-pick the one commit on top of master), or would you prefer that I do?

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKhronosGroup%2FOpenXR-SDK%2Fpull%2F60%3Femail_source%3Dnotifications%26email_token%3DAKRSM3XFPS4V3L57U7HCI3TP27655A5CNFSM4HYZCGEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX4QE3I%23issuecomment-502858349&data=02%7C01%7Czheng.qin%40microsoft.com%7Ca901dec7446d4490dc6308d6f36af773%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636964038082295899&sdata=5xygLlUxRrFAE3H7aXzTDwLMEhXTjLRSOkL7Ec%2FycUE%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKRSM3RHY6YX6MRJY24LNADP27655ANCNFSM4HYZCGEA&data=02%7C01%7Czheng.qin%40microsoft.com%7Ca901dec7446d4490dc6308d6f36af773%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636964038082305901&sdata=rj0MiHCcFc6hu4eXy3zW8LOp2SF5oUIMu%2FRlbU%2FeF4Q%3D&reserved=0>.

2019-06-17 22:28 UTC, zheqiMicrosoft commented
I just rebased the PR. Can you double check if that works please? Thanks!

Best,
Kevin

________________________________
发件人: Ryan A. Pavlik <notifications@github.com>
发送时间: Monday, June 17, 2019 2:30:06 PM
收件人: KhronosGroup/OpenXR-SDK
抄送: Kevin Qin; Author
主题: Re: [KhronosGroup/OpenXR-SDK] Fix build error with shlwapi function (#60)


Can't rebase this automatically on master - can you do that (or just cherry-pick the one commit on top of master), or would you prefer that I do?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKhronosGroup%2FOpenXR-SDK%2Fpull%2F60%3Femail_source%3Dnotifications%26email_token%3DAKRSM3XFPS4V3L57U7HCI3TP27655A5CNFSM4HYZCGEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX4QE3I%23issuecomment-502858349&data=02%7C01%7Czheng.qin%40microsoft.com%7Ca901dec7446d4490dc6308d6f36af773%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636964038082295899&sdata=5xygLlUxRrFAE3H7aXzTDwLMEhXTjLRSOkL7Ec%2FycUE%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKRSM3RHY6YX6MRJY24LNADP27655ANCNFSM4HYZCGEA&data=02%7C01%7Czheng.qin%40microsoft.com%7Ca901dec7446d4490dc6308d6f36af773%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636964038082305901&sdata=rj0MiHCcFc6hu4eXy3zW8LOp2SF5oUIMu%2FRlbU%2FeF4Q%3D&reserved=0>.

2019-06-17 22:57 UTC, rpavlik commented
Looks reasonable to me, will let @yl-msft decide if it's good to merge, given the related work, apparently already coordinated.

2019-06-17 22:58 UTC, zheqiMicrosoft commented
Thanks!

From: Ryan A. Pavlik <notifications@github.com>
Sent: Monday, June 17, 2019 3:58 PM
To: KhronosGroup/OpenXR-SDK <OpenXR-SDK@noreply.github.com>
Cc: Kevin Qin <Zheng.Qin@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [KhronosGroup/OpenXR-SDK] Fix build error with shlwapi function (#60)


Looks reasonable to me, will let @yl-msft<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyl-msft&data=02%7C01%7Czheng.qin%40microsoft.com%7C52def81448e34399bac008d6f37739ed%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636964090732183388&sdata=8Lk4hAlCOubO8F%2FdbNKuk21ZoG8wIifwwu9bv6Uja2U%3D&reserved=0> decide if it's good to merge, given the related work, apparently already coordinated.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKhronosGroup%2FOpenXR-SDK%2Fpull%2F60%3Femail_source%3Dnotifications%26email_token%3DAKRSM3TCS3IRB3NWRX7SM2DP3AJG7A5CNFSM4HYZCGEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX4VWJA%23issuecomment-502881060&data=02%7C01%7Czheng.qin%40microsoft.com%7C52def81448e34399bac008d6f37739ed%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636964090732193384&sdata=STU1mhXdPDNPnpwLOkmGDohhB5cyyEyUwupA51uW8vg%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKRSM3QBOZLCJN5LFP5JKZTP3AJG7ANCNFSM4HYZCGEA&data=02%7C01%7Czheng.qin%40microsoft.com%7C52def81448e34399bac008d6f37739ed%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636964090732198382&sdata=UyWS%2FJQ2CiiokT5i8aoOiDZmynKhJ7fIkVUY9%2BAUTmc%3D&reserved=0>.

2019-06-18 23:13 UTC, yl-msft requested changes

2019-06-18 23:13 UTC, yl-msft commented on src/common/filesystem_utils.cpp
> +        LPWIN32_FIND_DATAA file_data;
This is an output struct.  If you left this as a random pointer, the Find... functions below won't work correctly (or writing into random memory)

2019-06-19 06:43 UTC, zheqiMicrosoft commented on src/common/filesystem_utils.cpp
> +        LPWIN32_FIND_DATAA file_data;
I see. Thanks! I changed the file_data to WIN32_FIND_DATAA

2019-06-19 16:17 UTC, yl-msft approved these changes

2019-06-19 17:45 UTC, merged