Simplify loader
KhronosGroup/OpenXR-SDK-Source pull request #69
Opened 2019-06-25 23:08 UTC by rpavlik

The main thing I did here is the same basic cleanup I performed on the validation layer a while ago: replaced duplicated "lock, look up in map, unlock" logic with classes that do that all in one call.

The manual new and delete made me nervous so I switched nearly all of them to unique_ptrs now too.

It also changes a few XR_ERROR_VALIDATION_FAILURE into XR_ERROR_HANDLE_INVALID for consistency.

Handful of other changes too. De-duplicates and makes it easier at least for me to read and follow, hopefully for others too.

Commit messages should be useful.

2019-06-26 14:03 UTC, rpavlik commented
ci error is 32-bit reinterpret_cast of handles, relatively easy fix.

2019-06-26 15:55 UTC, rpavlik commented
OK, that should have fixed it in such a way that it won't break again (and neither will other places in the source since I went through and unified things.)

2019-06-26 17:59 UTC, brycehutchings requested changes

2019-06-26 17:59 UTC, brycehutchings commented on src/loader/loader_instance.hpp
> +            auto here = it;
I think you can avoid this iterator dance by using the return value from erase which is an iterator pointing to the next element.

2019-06-26 17:59 UTC, brycehutchings commented on src/loader/loader_instance.hpp
> +        // Internal error in loader or runtime.
I would be careful here. The loader isn't great at managing handle lifetimes. For example, if an app calls xrDestroyActionSet then all of the child actions are also destroyed, but the loader won't clean up those actions. So a runtime may return newly created action handles that reuse existing handle values, which is legit, but it will cause this error to happen.

2019-06-26 18:39 UTC, rpavlik commented on src/loader/loader_instance.hpp
> +            auto here = it;
Ah, cool - looked it up, and looks like the overloads that take an iterator do actually return one. Cool, will do.

2019-06-26 18:42 UTC, rpavlik commented on src/loader/loader_instance.hpp
> +        // Internal error in loader or runtime.
Ah, good point. This was just a transplant of the logic that was spread out all over before, but I can address that.

2019-06-26 21:04 UTC, brycehutchings approved these changes

2019-06-27 14:10 UTC, rpavlik commented
OK, got 32-bit compilation working locally, which inexplicably revealed an unresolved symbol error that didn't show up when building 64-bit. Hopefully this get the job done.

2019-06-27 15:10 UTC, rpavlik commented
OK, got this tested to at least build on Windows. Bizarre that clang was fine building it on Linux.

2019-06-27 20:40 UTC, merged