Make Loader Exception Free
KhronosGroup/OpenXR-SDK-Source pull request #70
Opened 2019-06-26 18:50 UTC by zheqiMicrosoft

Try to make exception free by doing the following:
1. For Exceptions are thrown and caught directly by the function that throws. These instances are changed to early return with a corresponding XrResult and logging, if any.
2. For Throws that are the result of a catch(..) with some “unknown error” or “bad alloc” logging. Remove these instances
3. Remove all catches directly.
4. Change JSON_USE_EXCEPTION to be defined as 0 so jsoncpp will not throw exception.

Note: This PR does not touch throws and catches in all tests, core_validation and xr_generated_core_validation. core_validation and xr_generated_core_validation are intended to be used by application developers and not part of the loader.

2019-06-26 18:50 UTC, zheqiMicrosoft commented
@daveh-lunarg Here is my PR for making loader exception free. Thanks!

2019-06-26 19:19 UTC, rpavlik commented
Looks like you also changed the ApiDump layer as well, which is probably fine - haven't gotten thru it - but is above and beyond doing just the loader. :)

2019-06-26 19:24 UTC, rpavlik requested changes
In the files I made it through, I found one change. It's a bit hard to read with all the indentation changes - any way you could split this into multiple commits, where only the last one does the "simple" removal of try-catch?

Also, I'm hoping to land #69 soon which would collide with this, though probably making it somewhat simpler due to centralizing logic, just as a heads-up. Your review there would be appreciated.

2019-06-26 19:24 UTC, rpavlik commented on src/api_layers/api_dump.cpp
> +    XrGeneratedDispatchTable *next_dispatch = g_instance_dispatch_map[instance];
Please revert this change (and any others like it) - it was recently included because of #53

2019-06-26 20:54 UTC, zheqiMicrosoft commented
I didn't realize that ApiDump is another layer. I will make a new PR with the same changes the ones in api_dump_generator.py and api_dump.cpp. And I will make sure indent change in a separate commit than the removal of try...catches. Thanks!

2019-06-26 20:54 UTC, closed without merging

2019-06-26 22:43 UTC, zheqiMicrosoft commented
Hi Ryan, 
May I ask what's the estimate timeline of [#69](https://github.com/KhronosGroup/OpenXR-SDK/pull/69)? Thanks!

2019-06-27 13:44 UTC, rpavlik commented
Well, I got one approved review, hoping for another soon so I feel comfortable merging it. Also need to figure out the Windows build issue. If your revision of this lands first, I can rebase no problem, just wanted to mention it in case building on that one made the revision job any easier.

2019-06-27 16:25 UTC, zheqiMicrosoft commented
I see. Thanks!


From: Ryan A. Pavlik <notifications@github.com>
Sent: Thursday, June 27, 2019 6:45 AM
To: KhronosGroup/OpenXR-SDK <OpenXR-SDK@noreply.github.com>
Cc: Kevin Qin <Zheng.Qin@microsoft.com>; State change <state_change@noreply.github.com>
Subject: Re: [KhronosGroup/OpenXR-SDK] Make Loader Exception Free (#70)


Well, I got one approved review, hoping for another soon so I feel comfortable merging it. Also need to figure out the Windows build issue. If your revision of this lands first, I can rebase no problem, just wanted to mention it in case building on that one made the revision job any easier.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKhronosGroup%2FOpenXR-SDK%2Fpull%2F70%3Femail_source%3Dnotifications%26email_token%3DAKRSM3QWSHLJJZ7AULS5NZDP4S737A5CNFSM4H3VCUL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYXFE3A%23issuecomment-506352236&data=02%7C01%7Czheng.qin%40microsoft.com%7C56b0c18091c749265a9708d6fb059550%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636972398733615260&sdata=F6ngJZJq8LJEl0tl8rr%2FVINd3fSgcEOzs9TfqLd07yc%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKRSM3SS2P63IHPAIZAMOITP4S737ANCNFSM4H3VCULQ&data=02%7C01%7Czheng.qin%40microsoft.com%7C56b0c18091c749265a9708d6fb059550%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636972398733615260&sdata=5tUd7HccLlOcaR5gZN7U4r4Cu1271%2BT2gCCVzIREYnY%3D&reserved=0>.

2019-06-27 20:41 UTC, rpavlik commented
It's now merged. I can take a whack at porting your changes, if you like, otherwise if you make them on the old base because it works better for you, I can do the rebase for you and let you review it.

2019-06-27 20:43 UTC, zheqiMicrosoft commented
Thanks! I think I will just rebase it.

From: Ryan A. Pavlik <notifications@github.com>
Sent: Thursday, June 27, 2019 1:42 PM
To: KhronosGroup/OpenXR-SDK <OpenXR-SDK@noreply.github.com>
Cc: Kevin Qin <Zheng.Qin@microsoft.com>; State change <state_change@noreply.github.com>
Subject: Re: [KhronosGroup/OpenXR-SDK] Make Loader Exception Free (#70)


It's now merged. I can take a whack at porting your changes, if you like, otherwise if you make them on the old base because it works better for you, I can do the rebase for you and let you review it.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKhronosGroup%2FOpenXR-SDK%2Fpull%2F70%3Femail_source%3Dnotifications%26email_token%3DAKRSM3TGECYXBFTSFT3IUODP4UQYPA5CNFSM4H3VCUL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYYJ7II%23issuecomment-506503073&data=02%7C01%7Czheng.qin%40microsoft.com%7C44f246a4da174119762508d6fb3fddbb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636972649051666996&sdata=fn7mWURiXJltxBoFnSDdhfELRoa%2B4KAEaVP9EbKsKIA%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKRSM3UWF2YEDQOGVFSMIETP4UQYPANCNFSM4H3VCULQ&data=02%7C01%7Czheng.qin%40microsoft.com%7C44f246a4da174119762508d6fb3fddbb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636972649051666996&sdata=NRO1sXFObmbbHJGpYS2qKiOQkzNNi0wZw7K0tFG9YMg%3D&reserved=0>.

2019-06-27 20:56 UTC, rpavlik commented
I actually just looked at the diff in a viewer with whitespace ignored, and it is hopefully pretty easy to rebase - sorry about the mess I made for you.

Is this really all that the folks setting these requirements need - that try/catch and the manual throws are removed? Removing the manual throws makes sense, but the try/catch removal looks to me like removing the try/catch is risking an exception (thrown by a standard library component) escaping the ABI uncaught. That said, I've been lucky enough to usually be permitted exception usage, so I'm not very familiar with stringently avoiding them.

2019-06-27 21:09 UTC, zheqiMicrosoft commented
Yes. According to my understanding that’s all we need. https://github.com/KhronosGroup/OpenXR-SDK/issues/52 Maybe we can discuss on this thread so everyone can see it. Thanks for the help!

From: Ryan A. Pavlik <notifications@github.com>
Sent: Thursday, June 27, 2019 1:56 PM
To: KhronosGroup/OpenXR-SDK <OpenXR-SDK@noreply.github.com>
Cc: Kevin Qin <Zheng.Qin@microsoft.com>; State change <state_change@noreply.github.com>
Subject: Re: [KhronosGroup/OpenXR-SDK] Make Loader Exception Free (#70)


I actually just looked at the diff in a viewer with whitespace ignored, and it is hopefully pretty easy to rebase - sorry about the mess I made for you.

Is this really all that the folks setting these requirements need - that try/catch and the manual throws are removed? Removing the manual throws makes sense, but the try/catch removal looks to me like removing the try/catch is risking an exception (thrown by a standard library component) escaping the ABI uncaught. That said, I've been lucky enough to usually be permitted exception usage, so I'm not very familiar with stringently avoiding them.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKhronosGroup%2FOpenXR-SDK%2Fpull%2F70%3Femail_source%3Dnotifications%26email_token%3DAKRSM3QE2WEL5HHWBRI3C2TP4USPTA5CNFSM4H3VCUL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYYLGQA%23issuecomment-506508096&data=02%7C01%7Czheng.qin%40microsoft.com%7C71b722188e7d453dc08d08d6fb41eb0c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636972657863798854&sdata=lKE8wN8kI0YpXU2SSpcSpAlX4RPqT1FN1pwrINDIx9E%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKRSM3TQK6VNSXGYKEGTX6TP4USPTANCNFSM4H3VCULQ&data=02%7C01%7Czheng.qin%40microsoft.com%7C71b722188e7d453dc08d08d6fb41eb0c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636972657863808849&sdata=y2I9dIlYkYQUUP0kJg2c%2BkGAFKIbvK%2BY8%2BQkv1k3Go0%3D&reserved=0>.