Make Loader Exception Free
KhronosGroup/OpenXR-SDK-Source pull request #76
Opened 2019-06-28 00:56 UTC by zheqiMicrosoft

Try to make Loader exception free by doing the following:
1. For Exceptions are thrown and caught directly by the function that throws. These instances are changed to early return with a corresponding XrResult and logging, if any.
2. For Throws that are the result of a catch(..) with some “unknown error” or “bad alloc” logging. Remove these instances
3. Remove all catches directly.
4. Change JSON_USE_EXCEPTION to be defined as 0 so jsoncpp will not throw exception.

2019-06-28 00:58 UTC, zheqiMicrosoft commented
@rpavlik @daveh-lunarg Here is the new PR. The only difference with the previous one is that this one does not touch api_dump and things are separated into 2 commits. First commits adjust indentation, and second commit make the real change. Thanks!

2019-06-28 15:57 UTC, rpavlik commented
See issue #52

2019-07-01 20:45 UTC, daveh-lunarg commented on doc/loader/OpenXR_loader_design.html
> -<div class="title">Exceptions</div>
This html is built from the loader design .adoc files in https://gitlab.khronos.org/openxr/openxr/tree/master/specification/loader. These changes should be made there or will be lost on next build/update.

2019-07-01 21:55 UTC, daveh-lunarg requested changes
This all looks good to me.  I didn't test but by inspection I think the python changes do the right thing for the generated code as well.

Looks good to push pending removal of the html edits (and a corresponding MR for the loader .adoc files).

2019-07-02 14:29 UTC, rpavlik commented
@daveh-lunarg the loader adoc files are not public right now - this is why I wanted to make them public :)

2019-07-03 23:04 UTC, zheqiMicrosoft commented
Hi @daveh-lunarg , unfortunately I don't have access to the link you sent(https://gitlab.khronos.org/openxr/openxr/tree/master/specification/loader). Is there any other way I can modify the .adoc file? Thanks!

2019-07-09 14:01 UTC, rpavlik commented
@zheqiMicrosoft I'd just skip it - leave the modified HTML, and I'll open an issue internally to sync the source back. There's already a separate issue to publish the loader doc adoc files.

2019-07-12 19:47 UTC, zheqiMicrosoft commented
@rpavlik Hi Ryan, is there any other changes I need to make for this PR? Thanks!

2019-07-17 21:59 UTC, zheqiMicrosoft commented
@rpavlik @daveh-lunarg Hi Dave and Ryan, I just removed the doc/loader/OpenXR_loader_design.html file from this PR since it's generated. Thanks!

2019-07-22 21:28 UTC, RafaelCintron commented
Not having this change is a blocker for having an OpenXR backend in Chromium.  

@rpavlik and @daveh-lunarg how do we move forward on getting this in?

2019-07-23 14:50 UTC, rpavlik commented
I guess my main concern is that removing the catches isn't preventing exceptions, it's allowing exceptions to sneak out of the ostensibly-C ABI. The runtime shouldn't let exceptions escape, but there are standard library containers used and I haven't audited the calls (or added `nothrow`) to make sure that they won't throw.

2019-07-24 17:09 UTC, RafaelCintron commented
The version of the standard library that Chromium uses has been compiled to not throw exceptions.  This pull request eliminates throwing from the loader itself.  Is there any other exception throwing source we should be concerned about?

2019-07-24 18:45 UTC, rpavlik commented
Ah, ok. Still makes me nervous we might leak exceptions to those who aren't using such a standard library, but I can probably propose a change later.

2019-07-24 19:19 UTC, rpavlik commented
OK, so I rebased it, then made some changes to allow non-Chromium users to avoid leaking exceptions - see #80. I'd rather wait for that whole thing (including this change) to merge than to merge this without the protection for non-chromium users, especially since chromium can presumably use a local fork right now anyway.

2019-07-25 18:27 UTC, rpavlik commented
Thanks for your work on this and your patience. I've rebased it into #80 which is now merged!

2019-07-25 18:27 UTC, closed without merging